export const baseSchema = {
tasks: `
    ++id,
    title,
    status,
    dueDate,
    businessDaysLeft,
    createdAt,
    updatedAt,

    lawsuitNumber,
    lawsuitParties,
    circuit,
    rankingPriority,

    assignedToEmail,
    assignedRole,
    ttl,
    [lawsuitNumber+status],
    [rankingPriority+status],
    [dueDate+status]
  `,
  lawsuits: `
  ++id, 
  number,
  circuit,
  status,
  assisted, 
  isDefendant,  
  source,
  awarenessDate,
  initialDeadline, 
  deadline, 
  givenDeadline, 
  parties, 
  normalizedParties, 
  searchText, 
  [status+circuit], 
  [status+assisted],
  [circuit+assisted], 
  [status+isDefendant],
  [number+assisted],
  [number+deadline],
  [deadline+number], 
  [assisted+number],
  [assisted+status],
  [assisted+deadline],
  [deadline+assisted],
  [status+deadline],
  [deadline+status],
  [isDefendant+assisted]
  `,
  holidays: `
  ++id,
  startDate,
  endDate,
  name,
  isNational,
  [startDate+endDate],
  [endDate+startDate]
`}
